import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ImageDialog } from '@/components/editor/ImageDialog'
import { CoverImagePreview } from '@/components/editor/CoverImagePreview'
import { readImageDimensions, uploadImage, validateImageUrl } from '@/features/posts/media/client'
vi.mock('@/features/posts/media/client', () => ({ uploadImage: vi.fn(), validateImageUrl: vi.fn(), readImageDimensions: vi.fn() }))
const ready = { src: 'https://images.example.com/photo.webp', alt: '', width: 800, height: 600 }
const file = () => new File(['photo bytes'], 'circuit.png', { type: 'image/png' })
beforeEach(() => {
  vi.resetAllMocks()
  vi.mocked(uploadImage).mockResolvedValue(ready)
  vi.mocked(validateImageUrl).mockImplementation(async url => url)
  vi.mocked(readImageDimensions).mockResolvedValue({ width: 800, height: 600 })
})
describe('shared accessible image workflow', () => {
  it.each(['text/plain', 'text/html'])('preserves clipboard %s even when an image rendition is present', type => {
    render(<ImageDialog editorId="author-a" onSave={vi.fn()} onClose={vi.fn()} />)
    const accepted = fireEvent.paste(screen.getByLabelText('Image description (alt text)'), {
      clipboardData: { files: [file()], getData: (format: string) => format === type ? 'Copied text' : '' },
    })
    expect(accepted).toBe(true)
    expect(screen.queryByText('Selected: circuit.png')).not.toBeInTheDocument()
    expect(uploadImage).not.toHaveBeenCalled()
  })
  it('uses the same upload and metadata path for pasted and selected files', async () => {
    const save = vi.fn()
    const close = vi.fn()
    render(<ImageDialog editorId="author-a" onSave={save} onClose={close} />)
    const selected = file()
    fireEvent.change(screen.getByLabelText('Image file'), { target: { files: [selected] } })
    fireEvent.click(screen.getByRole('button', { name: 'Upload image / retry' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Use image' })).toBeEnabled())
    expect(uploadImage).toHaveBeenCalledWith(selected, 'author-a', expect.any(Function), expect.any(AbortSignal))
    fireEvent.click(screen.getByRole('button', { name: 'Use image' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Describe what the image communicates')
    expect(save).not.toHaveBeenCalled()
    fireEvent.change(screen.getByLabelText('Image description (alt text)'), { target: { value: 'A circuit board with test points labeled in blue' } })
    fireEvent.click(screen.getByRole('button', { name: 'Use image' }))
    await waitFor(() => expect(save).toHaveBeenCalledWith({ ...ready, alt: 'A circuit board with test points labeled in blue' }))
    const pasted = file()
    fireEvent.paste(screen.getByRole('dialog'), { clipboardData: { getData: () => '', files: [pasted] } })
    fireEvent.click(screen.getByRole('button', { name: 'Upload image / retry' }))
    await waitFor(() => expect(uploadImage).toHaveBeenLastCalledWith(pasted, 'author-a', expect.any(Function), expect.any(AbortSignal)))
    expect(close).toHaveBeenCalled()
  })
  it('announces progress, keeps failed file input and retries without mutating the document', async () => {
    const save = vi.fn()
    const pasted = file()
    let fail!: (error: Error) => void
    vi.mocked(uploadImage).mockImplementationOnce((_file, _editorId, progress) => { progress(48); return new Promise((_resolve, reject) => { fail = reject }) })
    render(<ImageDialog editorId="author-a" initialFile={pasted} onSave={save} onClose={vi.fn()} />)
    fireEvent.click(screen.getByRole('button', { name: 'Upload image / retry' }))
    expect(screen.getByRole('status')).toHaveTextContent('48%')
    expect(screen.getByRole('button', { name: 'Use image' })).toBeDisabled()
    await act(async () => fail(new Error('Connection lost. Retry.')))
    expect(screen.getByRole('alert')).toHaveTextContent('Your document input is preserved')
    expect(screen.getByText('Selected: circuit.png')).toBeVisible()
    expect(save).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Upload image / retry' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Use image' })).toBeEnabled())
    expect(uploadImage).toHaveBeenLastCalledWith(pasted, 'author-a', expect.any(Function), expect.any(AbortSignal))
  })
  it('rejects unsupported and oversized files before network upload', () => {
    render(<ImageDialog editorId="author-a" onSave={vi.fn()} onClose={vi.fn()} />)
    fireEvent.change(screen.getByLabelText('Image file'), { target: { files: [new File(['<svg/>'], 'image.svg', { type: 'image/svg+xml' })] } })
    expect(screen.getByRole('alert')).toHaveTextContent('not supported')
    expect(screen.getByRole('button', { name: 'Upload image / retry' })).toBeDisabled()
    fireEvent.paste(screen.getByRole('dialog'), { clipboardData: { getData: () => '', files: [new File([new Uint8Array(4 * 1024 * 1024 + 1)], 'large.png', { type: 'image/png' })] } })
    expect(screen.getByRole('alert')).toHaveTextContent('exceeds 4 MB')
    expect(uploadImage).not.toHaveBeenCalled()
  })
  it('allows deliberate decorative inline images but requires cover descriptions', async () => {
    const save = vi.fn()
    render(<ImageDialog editorId="author-a" initial={ready} onSave={save} onClose={vi.fn()} />)
    fireEvent.click(screen.getByLabelText('This image is decorative'))
    fireEvent.click(screen.getByRole('button', { name: 'Use image' }))
    await waitFor(() => expect(save).toHaveBeenCalledWith(ready))
  })
  it('validates remote URLs and leaves descriptions available when a URL fails', async () => {
    vi.mocked(validateImageUrl).mockRejectedValueOnce(new Error('Use a configured HTTPS image host'))
    const save = vi.fn()
    render(<ImageDialog cover editorId="author-a" onSave={save} onClose={vi.fn()} />)
    expect(screen.queryByLabelText('This image is decorative')).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Image URL'), { target: { value: 'https://unknown.example/photo.jpg' } })
    fireEvent.change(screen.getByLabelText('Image description (alt text)'), { target: { value: 'Circuit board with labeled ports' } })
    fireEvent.click(screen.getByRole('button', { name: 'Use image' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('configured HTTPS')
    expect(save).not.toHaveBeenCalled()
    expect(screen.getByLabelText('Image description (alt text)')).toHaveValue('Circuit board with labeled ports')
    fireEvent.change(screen.getByLabelText('Image URL'), { target: { value: 'https://images.example.com/photo.webp' } })
    fireEvent.click(screen.getByRole('button', { name: 'Use image' }))
    await waitFor(() => expect(save).toHaveBeenCalledWith({ ...ready, alt: 'Circuit board with labeled ports' }))
  })
  it('cancels in-flight uploads when the dialog unmounts', () => {
    vi.mocked(uploadImage).mockReturnValue(new Promise(() => {}))
    const view = render(<ImageDialog editorId="author-a" initialFile={file()} onSave={vi.fn()} onClose={vi.fn()} />)
    fireEvent.click(screen.getByRole('button', { name: 'Upload image / retry' }))
    const signal = vi.mocked(uploadImage).mock.calls[0][3]
    view.unmount()
    expect(signal.aborted).toBe(true)
  })
})
describe('cover failure visibility', () => {
  it('shows a retryable failure instead of hiding a broken cover', async () => {
    render(<CoverImagePreview src={ready.src} alt="Circuit board" editorId="author-a" />)
    const image = await screen.findByRole('img', { name: 'Circuit board' })
    fireEvent.error(image)
    expect(screen.getByRole('alert')).toHaveTextContent('could not be loaded')
    fireEvent.click(screen.getByRole('button', { name: 'Retry cover preview' }))
    expect(await screen.findByRole('img', { name: 'Circuit board' })).toBeVisible()
  })
})
