import { createClient } from '@supabase/supabase-js'
import { test, expect } from '../fixtures'

const admin = () => createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } })
async function login(page: import('@playwright/test').Page) {
  await page.goto('/login')
  await page.getByLabel('Email address').fill('e2e-test@playwright.local')
  await page.getByLabel('Password', { exact: true }).fill(process.env.E2E_TEST_PASSWORD ?? 'E2eTestPassword123!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
}

test('new writing recovers after offline interruption and resumes private autosave', async ({ page, context }) => {
  await login(page)
  await page.goto('/dashboard/posts/new')
  await expect(page.getByText('Changes will autosave as a private working copy.')).toBeVisible()
  const editorUrl = page.url()
  const documentId = new URL(editorUrl).searchParams.get('draft')!
  const title = `Offline recovery ${Date.now()}`
  await context.setOffline(true)
  await page.getByLabel('Post title').fill(title)
  await page.locator('[contenteditable="true"]').fill('Writing kept through an offline interruption.')
  await expect(page.getByText('Autosave failed', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.keys(localStorage).some(key => key.startsWith('post-recovery:')))).toBe(true)
  await context.setOffline(false)
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await expect(page.getByRole('region', { name: 'Draft recovery' })).toBeVisible()
  await expect(page.getByLabel('Post title')).toHaveValue('')
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await expect(page.getByLabel('Post title')).toHaveValue(title)
  await expect(page.locator('[contenteditable="true"]')).toContainText('Writing kept through an offline interruption.')
  await expect(page.getByText('Working copy saved', { exact: true })).toBeVisible()
  const saved = await admin().from('post_working_copies').select('values, post_id').eq('document_id', documentId).single()
  expect(saved.error).toBeNull()
  expect(saved.data?.post_id).toBeNull()
  expect(saved.data?.values.title).toBe(title)
  await page.getByRole('button', { name: 'All posts', exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard\/posts$/)
  await page.goto('/dashboard/posts/new')
  await expect(page.getByRole('link', { name: `Continue ${title}` })).toBeVisible()
  await page.getByRole('link', { name: `Continue ${title}` }).click()
  await expect(page).toHaveURL(editorUrl)
  await expect(page.getByRole('region', { name: 'Draft recovery' })).toBeVisible()
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await page.getByRole('button', { name: 'Create Post', exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard\/posts\/[^/]+\/edit$/)
  expect((await admin().from('post_working_copies').select('document_id').eq('document_id', documentId)).data).toEqual([])
  await expect(page.getByRole('region', { name: 'Draft recovery' })).not.toBeVisible()
})

test('published edits autosave privately; multiple posts and tabs keep separate recovery', async ({ page, context, seedPostIds }) => {
  await login(page)
  const publishedId = seedPostIds[1]
  const before = (await admin().from('posts').select('title, content, status').eq('id', publishedId).single()).data
  await page.goto(`/dashboard/posts/${publishedId}/edit`)
  const title = `Private published edit ${Date.now()}`
  await page.getByLabel('Post title').fill(title)
  await expect(page.getByText('Working copy saved', { exact: true })).toBeVisible()
  expect((await admin().from('posts').select('title, content, status').eq('id', publishedId).single()).data).toEqual(before)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Draft recovery' })).toBeVisible()
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await expect(page.getByLabel('Post title')).toHaveValue(title)
  const other = await context.newPage()
  await other.goto(`/dashboard/posts/${seedPostIds[0]}/edit`)
  await expect(other.getByText('Changes will autosave as a private working copy.')).toBeVisible()
  await expect(other.getByLabel('Post title')).toHaveValue('E2E Draft Post One')
  await other.close()
  const second = await context.newPage()
  await second.goto(`/dashboard/posts/${publishedId}/edit`)
  await second.getByRole('button', { name: 'Restore', exact: true }).click()
  await second.getByLabel('Post title').fill('Winning tab text')
  await expect(second.getByText('Working copy saved', { exact: true })).toBeVisible()
  await page.getByLabel('Post title').fill('Conflicting tab text')
  await expect(page.getByText('Autosave failed', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Post title')).toHaveValue('Conflicting tab text')
  const server = await admin().from('post_working_copies').select('values').eq('document_id', publishedId).single()
  expect(server.data?.values.title).toBe('Winning tab text')
  expect((await admin().from('posts').select('title, content, status').eq('id', publishedId).single()).data).toEqual(before)
  await second.close()
})

test('expired sessions retain the editor and retry succeeds after signing in again', async ({ page, context, seedPostIds }) => {
  await login(page)
  await page.goto(`/dashboard/posts/${seedPostIds[2]}/edit`)
  await expect(page.getByText('Changes will autosave as a private working copy.')).toBeVisible()
  const editorUrl = page.url()
  await context.clearCookies()
  await page.getByLabel('Post title').fill('Writing after session expiry')
  await expect(page.getByText('Autosave failed', { exact: true })).toBeVisible()
  await expect(page).toHaveURL(editorUrl)
  await expect(page.getByLabel('Post title')).toHaveValue('Writing after session expiry')
  const signIn = await context.newPage()
  await login(signIn)
  await signIn.close()
  await page.getByRole('button', { name: 'Retry autosave', exact: true }).click()
  await expect(page.getByText('Working copy saved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save Draft', exact: true }).click()
  await expect(page.getByText('Post saved as draft', { exact: true })).toBeVisible()
  expect((await admin().from('posts').select('title').eq('id', seedPostIds[2]).single()).data?.title).toBe('Writing after session expiry')
  expect((await admin().from('post_working_copies').select('document_id').eq('document_id', seedPostIds[2])).data).toEqual([])
})

test('internal links and browser back warn; explicit discard removes unsaved recovery', async ({ page, context }) => {
  await login(page)
  await page.goto('/dashboard/posts/new')
  await expect(page.getByText('Changes will autosave as a private working copy.')).toBeVisible()
  await context.setOffline(true)
  await page.getByLabel('Post title').fill('Do not lose this draft')
  await expect(page.getByText('Autosave failed', { exact: true })).toBeVisible()
  const editorUrl = page.url()
  page.on('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'All posts', exact: true }).click()
  await expect(page).toHaveURL(editorUrl)
  await page.evaluate(() => history.back())
  await expect(page).toHaveURL(editorUrl)
  await expect(page.getByLabel('Post title')).toHaveValue('Do not lose this draft')
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await expect(page).toHaveURL(editorUrl)
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page).toHaveURL(editorUrl)
  page.removeAllListeners('dialog')
  page.on('dialog', dialog => dialog.accept())
  await context.setOffline(false)
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard\/posts$/)
  expect(await page.evaluate(documentId => Object.keys(localStorage).filter(key => key.includes(`:${documentId}:`)).length, new URL(editorUrl).searchParams.get('draft'))).toBe(0)
})
